// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQv5euysUmCN_gVF3UH_a4YAIprKGI5dA',
    appId: '1:824578840616:web:89625ccd3096551f737d1d',
    messagingSenderId: '824578840616',
    projectId: 'fcmtest-78202',
    authDomain: 'fcmtest-78202.firebaseapp.com',
    storageBucket: 'fcmtest-78202.appspot.com',
    measurementId: 'G-YNBTVX3HKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA34TmRsupHrJXXbWjjwTYy19GRIATJaJo',
    appId: '1:824578840616:android:3bd4cdcf73add2e5737d1d',
    messagingSenderId: '824578840616',
    projectId: 'fcmtest-78202',
    storageBucket: 'fcmtest-78202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSA9MWJ0Krbi-FiJoKvSvWKAqot1ege8Q',
    appId: '1:824578840616:ios:f03444444308208e737d1d',
    messagingSenderId: '824578840616',
    projectId: 'fcmtest-78202',
    storageBucket: 'fcmtest-78202.appspot.com',
    iosBundleId: 'com.example.flutterSplim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSA9MWJ0Krbi-FiJoKvSvWKAqot1ege8Q',
    appId: '1:824578840616:ios:f03444444308208e737d1d',
    messagingSenderId: '824578840616',
    projectId: 'fcmtest-78202',
    storageBucket: 'fcmtest-78202.appspot.com',
    iosBundleId: 'com.example.flutterSplim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQv5euysUmCN_gVF3UH_a4YAIprKGI5dA',
    appId: '1:824578840616:web:9eaad3ffcdf6cd1a737d1d',
    messagingSenderId: '824578840616',
    projectId: 'fcmtest-78202',
    authDomain: 'fcmtest-78202.firebaseapp.com',
    storageBucket: 'fcmtest-78202.appspot.com',
    measurementId: 'G-H5MF2G167Y',
  );

}